[target]
default = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
xargo = false
# see "armv7-unknown-linux-gnueabihf/Dockerfile"
image = "armv7-unknown-linux-gnueabihf:latest"
