apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suckless-hn-pvc
  namespace: suckless-hn
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

